/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAllChats: typeof import('./components/AppAllChats.vue')['default']
    AppChamada: typeof import('./components/AppChamada.vue')['default']
    AppChat: typeof import('./components/AppChat.vue')['default']
    AppHorarios: typeof import('./components/AppHorarios.vue')['default']
    AppProfissionais: typeof import('./components/AppProfissionais.vue')['default']
    AppSearch: typeof import('./components/AppSearch.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    AppTimeline: typeof import('./components/AppTimeline.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
